---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: microservices-demo
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./deploy/kubernetes/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: microservices-demo
  validation: client

